build:
  tags:
    - app-host
  only:
    - master
  stage: build
  script:
    - docker-compose build

deploy:
  tags:
    - app-host
  only:
    - master
  stage: deploy
  script:
    - docker-compose up -d

