version: "3.8"
services:
  startpage:
    build:
      context: .

    ports:
      - "5003:5003"

    volumes:
      - ./data:/app/data
    environment:
      - WEATHER_APIKEY=68c6f474a0a3c38fe8333f513738bf6c
