version: '3.8'

services:
    startpage:
            build:
                context: .
                dockerfile: Dockerfile
            container_name: startpage
            ports:
                - 5003:5003
            volumes:
                - /mnt/appdata/startpage:/app/data
            environment:
                - TZ=Europe/London
            restart: unless-stopped
            