// Generated by ts-to-zod
import { z } from "zod";

export type Weather = z.infer<typeof weatherSchema>;
export type WeatherDataResponse = z.infer<typeof weatherDataResponseSchema>;

export const weatherSchema = z.object({
  temperature: z.number(),
  description: z.string(),
  imageUrl: z.string(),
  feelsLike: z.number(),
  rainChance: z.number(),
});

export const weatherDataResponseSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  generationtime_ms: z.number(),
  utc_offset_seconds: z.number(),
  timezone: z.string(),
  timezone_abbreviation: z.string(),
  elevation: z.number(),
  current_units: z.object({
    time: z.string(),
    interval: z.string(),
    temperature_2m: z.string(),
    apparent_temperature: z.string(),
    precipitation: z.string(),
    weather_code: z.string(),
  }),
  current: z.object({
    time: z.string(),
    interval: z.number(),
    temperature_2m: z.number(),
    apparent_temperature: z.number(),
    precipitation: z.number(),
    weather_code: z.number(),
  }),
});
